global:
  acme:
    domain: steadops.local.steadforce.com
  istio:
    ingressGateway:
      namespace: istio-ingress

redpanda:
  statefulset:
    initContainers:
      setDataDirOwnership:
        enabled: true

subDomain: redpanda-console