global:
  acme:
    domain: steadops.local.steadforce.com
  istio:
    ingressGateway:
      namespace: istio-ingress

redpanda:
  statefulset:
    initContainers:
      setDataDirOwnership:
        enabled: true
  post_install_job:
    enabled: false
  post_upgrade_job:
    enabled: false

subDomain: redpanda-console