{{- if .Capabilities.APIVersions.Has "cluster.redpanda.com/v1alpha1" }}
apiVersion: cluster.redpanda.com/v1alpha1
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef: {}
  {{- if ((.Values.redpanda).podAntiAffinity) }}
  podAntiAffinity: {{ .Values.redpanda.podAntiAffinity | toYaml | nindent 4 }}
  {{- end }}
  clusterSpec:
    external:
      domain: customredpandadomain.local
    statefulset:
      initContainers:
        setDataDirOwnership:
          enabled: true
{{- end }}  